### ISSUE TITLE
need help compiling

### ISSUE THREAD

**Issue by hewr1993** [udevbe/tinyh264#1]
Hi there, I have a problem compiling .wasm and .js by myself. I just simply run ```rake``` and the generated .js contains `document` so there's no way to use it in a Web Worker. I wonder if there is any trick on compilation. Any help would be appreciated. 

Here's the formatted version of the official `TinyH264.js`. 
[TinyH264.js.txt](https://github.com/udevbe/tinyh264/files/2371530/TinyH264.js.txt)

And here's `TinyH264.js` compiled by myself. 
[TinyH264.compiled.js.txt](https://github.com/udevbe/tinyh264/files/2371529/TinyH264.compiled.js.txt)

My environment:  
emscripten 1.38.12
rake 12.3.0
llvm 9.0.0
System: MacOS 10.13.2

**Comment by Zubnix** [comment]
I'm a bit confused. Did you try using it in a webworker and did it fail as a result of the document reference? The generated .js is normally created by emscripten which includes code to detect in which kind of environment the .js is loaded, as such, the codepath that has the 'document' reference in it will not be triggered.

In fact, TinyH264 runs in a webworker in [Greenfield](https://github.com/udevbe/greenfield/tree/master/browser/public) without issues, be it with some modifications to support multiple decoding streams in a single webworker.

**Comment by hewr1993** [comment]
I found the problem. The generated `TinyH264.js` has a line
```js
ENVIRONMENT_IS_WEB = typeof window === "object";
```
Unfortunately, [TinyH264Decoder.js:36](https://github.com/udevbe/tinyh264/blob/master/wasm/TinyH264Decoder.js#L36) defines `window = this` and `TinyH264Decoder.js` is imported before `TinyH264.js`, which let `TinyH264.js` think it's in main thread instead of a web worker. Remove that line and everything works perfectly right now. Thank for your help! 

If you're interested, I'm trying to change the output from YUV to RGBA for convenience of `canvas`. With YUV, we need to render using WebGL and it's not capable of handling 1080P@100FPS on my computer.

**Comment by Zubnix** [comment]
Yeah doing 1080P@100FPS pure browser side is quite stretch. Much depends on the quality settings/decoding complexity of the h264 nal stream. The best I could get it with good/acceptable quality was around 40-45fps on a relatively fast machine (dell xps15). Alternatively you could look into boxed MP4 combined with the HTML5 media source extension, which basically delegates the decoding to the native browser part. It has however it's own sets of quirks and jumps, especially if you want to do single frame boxing.
