### ISSUE TITLE
use wasm extension via file-loader

### ISSUE THREAD

**Issue by koush** [udevbe/tinyh264#11]
```
        {
          test: /\.(wasm\.asset)$/i,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[contenthash].wasm'
              }
            },
          ],
        },
```

If the wasm extension is used, any web server that uses mime db will automatically serve up the correct mime type (wasm maps to application/wasm).

https://github.com/jshttp/mime-db/blob/master/db.json#L5325

Otherwise, it falls back to arraybuffer initialization.

**Comment by Zubnix** [comment]
I believe the reason I used .wasm.asset and not just plain .wasm is to work around the current horrible state of how js source packagers (webpack and others) deal with wasm resource files. They all try to be "smart" and implement their own [failing] wasm initialization code, all while the wasm generated by emscripten compiler comes with it's own initialization code. I believe I lost quite a bit of hair (while the remaining part turned grey) before resorting to plain file-loader.

**Comment by koush** [comment]
Good to know. I made this change with webpack (for a pwa that also loads it via a service worker), and it worked fine.
If you look closely at the change, you'll see I retain the .asset file extension, but use file-loader to rename it.

**Comment by Zubnix** [comment]
If it's not too much work, I'd be happy to accept a pull request from you. I could also do it myself, but then it wouldn't have your name on it :)

**Comment by Zubnix** [comment]
demo has been updated
