### ISSUE TITLE
Input format for decode()?

### ISSUE THREAD

**Issue by gliese1337** [udevbe/tinyh264#12]
How did you generate the sample files for the demo? I can see that they work, and do in fact decode to sensible sequential pictures, but when I try to feed it my own data I just get a series of ERROR and PARAM_SET_ERROR return codes--no PIC_RDYs. I am trying to feed it with individual NAL units parsed out of an MPEG-TS file.

**Comment by gliese1337** [comment]
For reference, I have tried all of the following:

1) Inputting complete PES packets, with multiple NALUs. In this case, I just get a bunch of PARAM_SET_ERROR codes.
2) Inputting all NALUs with the boundary pattern bytes stripped
3) Inputting all NALUs with the boundary pattern bytes intact
4) Omitting parameter NALUs, inputting the rest with boundary pattern bytes stripped.
5) Omitting parameter NALUs, inputting the rest with boundary pattern bytes intact.

**Comment by gliese1337** [comment]
A little more experimentation: using the sample files from the demo, if I segment out the individual NALUs from those, and decode them individually, I get a sequence of ERROR responses up until the last one of the file, which returns PIC_RDY. However, if I just try to decode the last NALU on its own, I get PARAM_SET_ERROR--so clearly, all the preceding content in the files is important, which makes me wonder why it returns ERROR rather than RDY for all that.

**Comment by Zubnix** [comment]
What profile are you using? I've only got it working with (restricted) baseline, using only I & P frames fed as entire AU. If it's of any help, here's a working gstreamer pipeline: https://github.com/udevbe/greenfield/blob/master/app-endpoint-native/src/x264_gst_encoder.c#L297

**Comment by gliese1337** [comment]
Ah, that's gotta be it. The README doesn't say anything about profile restrictions, so I was assuming it would Just Work, without requiring cooperation on the encoding side.

**Comment by Zubnix** [comment]
Good point, I will mention it in the readme.

**Comment by Zubnix** [comment]
Readme is been updated.
