### ISSUE TITLE
Trying to get tinyh264 compiled so that the demo runs

### ISSUE THREAD

**Issue by benbatya** [udevbe/tinyh264#19]
Hi,
    I have been trying to get tinyh264 to compile and work inorder to develop with it.
I can get the es module compiled but then when I try to use it with demo code, it never works.
I am using emsdk sdk-releases-upstream-ea6c89d964204d42c9e3c636b0b2f186ca97e5d4-64bit and node-12.18.1-64bit which are the current 'tot-upstream'.

I build the module with
`yarn install && yarn run build`
Then I copy es/* into demo/src/lib and change H264NALDecoder.worker.js:
`import { init } from './lib'; // 'tinyh264' `
Finally I build and run the demo:
`yarn install && yarn run build && yarn run start:dev`

Strangely, there;s diffs between the TinyH264.js in node-modules and the generated TinyH264.js.

I can't figure out what is causing the differences and I am not sure why the custom built module never completes loading (never gets to context.next==3 in TinyH264Worker,js)

Any help would be appreciated. Thanks!

**Comment by Zubnix** [comment]
It seems the latest supported emscripten version is 1.39.15, I've pushed a commit to reflect this.

**Comment by benbatya** [comment]
Hi @Zubnix thank you for the fast reply.
I will go back to that version.
I am wondering if emsdk's API is changing rapidly still or if its rate of change has slowed down a little still. 
I'm interesting in getting tinyh264 to build with the latest emsdk.

**Comment by benbatya** [comment]
Yes! Version 1.39.15 worked!
Thanks!
