### ISSUE TITLE
slice encoding

### ISSUE THREAD

**Issue by ktb92677** [udevbe/tinyh264#24]
I am noticing some odd artifacts on my screen when I enable slice based encoding... does tinyh264 support slice based encoding?

**Comment by Zubnix** [comment]
I believe it should in some form. I'm no h264 expert unfortunately so I can't tell you what it does and doesn't support. I use it in a sliced multi-threaded encoding setup myself without issues though: https://github.com/udevbe/greenfield/blob/master/app-endpoint-native/src/x264_gst_encoder.c#L236

**Comment by ktb92677** [comment]
Do you know what VBV values you are using? Could you try setting them?
