### ISSUE TITLE
No LICENCE file

### ISSUE THREAD

**Issue by bugQ** [udevbe/tinyh264#44]
I'm aware that `package.json` specifies MIT as the license, but without an actual copy of the license it's unclear from a legal standpoint whether this package is actually licensed at all.

**Comment by Zubnix** [comment]
Indeed, the project was forked from another project, who got the source code from the android project that used the apache license. So I guess licensing it under the apache license is the most fitting solution.

**Comment by Zubnix** [comment]
I've added the license file & updated the package.json
