### ISSUE TITLE
Pixelated Scaling

### ISSUE THREAD

**Issue by TiKevin83** [udevbe/tinyh264#46]
I'm looking to play back upscaled retro pixel art game footage in the browser. Currently `image-rendering: pixelated` in CSS doesn't apply to video, but the effect should be replicable via the Canvas API according to MDN docs. The goal would be to have the canvas and video scaled to the largest integer multiple that still fits within the browser window. It would be super useful to have this available in a WASM player with the CSS property not affecting video as currently the only reasonable solutions involve uploading footage prescaled using nearest-neighbor or area algorithms to 4k/8k.

**Comment by Zubnix** [comment]
This is outside the scope of tinyh264. this lib only decodes h264 to yuv color buffer, after that it's up to you how present it to the user.
