### ISSUE TITLE
demo link 

### ISSUE THREAD

**Issue by vasanthudhaya** [udevbe/tinyh264#5]
Hi @Zubnix Thanks for this wonderful repo. 

Need a demo link for my project reference, that will be very useful for me.

Thanks in advance.

**Comment by Zubnix** [comment]
Hi, I'm not sure I understand what you mean. You mean a demo website on how to use this codec?

**Comment by vasanthudhaya** [comment]
Hi @Zubnix exactly i need  a demo website on how to use this codec. Thanks for the reply

**Comment by Zubnix** [comment]
Here you go: https://github.com/udevbe/tinyh264/tree/master/demo

**Comment by vasanthudhaya** [comment]
Hi @Zubnix, the demo you have given was es6 format. I need a basic HTML5 structure demo. Can you please give that?

**Comment by Zubnix** [comment]
The demo requires webpack with file-loader & webworker plugin  to correctly build (other build systems that can provide a URL for a custom asset+webworker import should work too). Without those, it won't work without modifying tiny-h264 itself. So your best bet is to get webpack working in your editor first.
